version: '3.9'

services:
  web:
    container_name: web-apikey
    build:
      context: .
      dockerfile: Dockerfile
    command: ["./scripts/entrypoint.sh"]
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./app:/src/app
      - ./scripts:/src/scripts
